language: C
sudo: false

addons:
  apt:
    packages:
      - cabal-install-1.22
      - ghc-7.10.3
    sources:
      - hvr-ghc

cache:
  - $HOME/.cabal/
  - $HOME/.ghc

install:
  - export PATH=/$HOME/.cabal/bin:$opt/ghc/7.10.3/bin:/opt/cabal/1.22/bin:$PATH;
  - ./install_agda.sh

script:
  - cd src/
  - wget https://github.com/agda/agda-stdlib/archive/v0.12.tar.gz
  - tar -xvzf v0.12.tar.gz
  - agda -i agda-stdlib-0.12/src -i . linear/README.agda
