language: haskell
ghc: 7.8
sudo: false
cache:
  - $HOME/.cabal/
  - $HOME/.ghc

install:
  - cabal update
  - cabal install Agda

script:
  - cd src/
  - wget https://github.com/agda/agda-stdlib/archive/v0.12.tar.gz
  - tar -xvzf agda-stdlib-0.12.tar.gz
  - agda -i agda-stdlib-0.12/src -i . linear/README.agda
